-- AlterTable
ALTER TABLE "challenges" ADD COLUMN     "domains" "Category"[] DEFAULT ARRAY[]::"Category"[];

-- CreateTable
CREATE TABLE "challenge_assignments" (
    "id" TEXT NOT NULL,
    "challengeId" TEXT NOT NULL,
    "partnerId" TEXT NOT NULL,
    "status" "ChallengeStatus" NOT NULL DEFAULT 'ASSIGNED',
    "assignedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "challenge_assignments_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "challenge_assignments_partnerId_idx" ON "challenge_assignments"("partnerId");

-- CreateIndex
CREATE UNIQUE INDEX "challenge_assignments_challengeId_partnerId_key" ON "challenge_assignments"("challengeId", "partnerId");

-- AddForeignKey
ALTER TABLE "challenge_assignments" ADD CONSTRAINT "challenge_assignments_challengeId_fkey" FOREIGN KEY ("challengeId") REFERENCES "challenges"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "challenge_assignments" ADD CONSTRAINT "challenge_assignments_partnerId_fkey" FOREIGN KEY ("partnerId") REFERENCES "partners"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- Backfill (hand-written, not generated by Prisma): every existing challenge
-- gets its primary category as its only domain...
UPDATE "challenges" SET "domains" = ARRAY["category"]::"Category"[] WHERE "domains" IS NULL OR cardinality("domains") = 0;

-- ...and every existing challenge that already has a partner gets one
-- assignment row copying its current status, so nothing changes behaviour.
INSERT INTO "challenge_assignments" ("id", "challengeId", "partnerId", "status", "assignedAt")
SELECT gen_random_uuid()::text, "id", "assignedPartnerId", "status", "createdAt"
FROM "challenges"
WHERE "assignedPartnerId" IS NOT NULL
ON CONFLICT ("challengeId", "partnerId") DO NOTHING;
